image:
  tag: dev
  pullPolicy: Always
service:
  type: NodePort
ingress:
  host: user.local
  tls:
    enabled: false
secret:
  jwtSecret: jwt-secret-dev
  databaseUrlSecret: database-url-secret-dev

