{{- if .Values.ingress.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuer.name }}
spec:
  acme:
    email: {{ .Values.issuer.email }}
    server: {{ .Values.issuer.server }}
    privateKeySecretRef:
      name: {{ .Values.issuer.privateKeySecretName }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.className }}
{{- end }}