{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "user-service.fullname" . }}-ingress
  annotations:
    {{- if and .Values.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.issuer.name }}
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if and .Values.ingress.tls.enabled .Values.ingress.host }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }} #user
            pathType: Prefix
            backend:
              service:
                name: {{ include "user-service.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}